### ISSUE TITLE
1.0.1 release checklist

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/files_external_dropbox#19]
### Reason
- Release needed for having compatibility  with php 5.6 (version 1.0.0 vendor dependencies were built for php7+)
- This release will thus address #13 #18 

### QA
- [x] Create release branch (@patrickjahns  - https://github.com/owncloud/files_external_dropbox/tree/release/1.0.1 )
- [ ] ~~Create "$version Testplan"~~
- [ ] ~~Test and document in testplan => Final "Go" from QA (set 'QA-ready' label)~~
Test in combination with:
https://github.com/owncloud/core/pull/29225

###  Marketing
- no marketing required

### Documentation
- no changes in docs required

**Build & Marketplace release**

- [x] Bump version in info.xml
- [x] Update CHANGELOG.md
- [x] Create github tag for '$version'
- [x] Build and sign tarball from github tag '$version'
- [x] Upload to marketplace
- [x] Rename QA milestone to '$version'
- [x] Change CHANGELOG.md 'Unreleased' to '$version' and add a new 'Unreleased' section
- [x] Create PR to merge changes back to `master`

cc @pmaier1

**Comment by patrickjahns** [comment]
I think https://github.com/owncloud/files_external_dropbox/pull/21 should be included - so we should create a new branch ?

**Comment by Hemant-Mann** [comment]
The branch https://github.com/owncloud/files_external_dropbox/tree/release/1.0.1 is shown to be in sync with **master** branch

**Comment by patrickjahns** [comment]
@SergioBertolinSG 
has created a new branch from master for QA

**Comment by patrickjahns** [comment]
@SergioBertolinSG @Hemant-Mann 
With the changes / fixes being introduced right now, I'd propose to bump the minor version and have a `1.1.0` release - to be done when #27 is fixed

**Comment by Hemant-Mann** [comment]
Sounds Good 👍

**Comment by SergioBertolinSG** [comment]
Tested and working fine. Only this issue is left https://github.com/owncloud/files_external_dropbox/issues/27

It will be fixed in following versions.

**Comment by patrickjahns** [comment]
@Hemant-Mann 
Once the lowercasing #27 is fixed - we can plan the next release (1.1.0) -> closing since 1.0.1 is released

**Comment by Hemant-Mann** [comment]
@patrickjahns I commented on your review and there is nothing more to do in #28 as @PVince81 pointed out https://github.com/owncloud/files_external_dropbox/pull/28#issuecomment-362234401
